version: "3.5"

services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: test-php-frm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APP_PATH_HOST}/logs/xdebug:/var/log/xdebug
      - ${APP_PATH_HOST}/logs/redis:/var/log/redis
      - ${REDIS_PATH_DATA}:/var/lib/redis
    working_dir: ${APP_PATH_CONTAINER}
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.222.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - "3000:3000"
    networks:
      - internal

  nginx:
    build:
      context: docker/nginx
    container_name: test-nginx
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APP_PATH_HOST}/logs/nginx:/var/log/nginx
#      - ${APP_PATH_HOST}/logs/xdebug:/var/log/xdebug
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - php-fpm
    networks:
      - internal

  mysql:
    build:
      context: ./docker/mysql
    container_name: test-mysql
    command: --default-authentication-plugin=mysql_native_password
    user: '1000'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwertynet
      MYSQL_DATABASE: dbsite
      MYSQL_USER: admin
      MYSQL_PASSWORD: user_password
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    ports:
      - "33060:3306"
    depends_on:
      - nginx
    networks:
      internal:
        ipv4_address: 192.168.222.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: test-phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: user_password
    volumes:
      - /session
    networks:
      - internal


networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28
